Iter13
stranik28/MetricsCollector pull request #20
Opened 2024-05-12 17:34 UTC by stranik28

2024-05-13 07:22 UTC, edylcrm requested changes

2024-05-13 07:22 UTC, edylcrm commented on internal/server/storage/dbConnect.go
> +func Connect(connectURL string, ctx context.Context) (*sql.DB, error) {
Принято всегда context передавать первым параметром

2024-05-13 07:22 UTC, edylcrm commented on internal/server/storage/dbStorage.go
> +func saveMetricsToDB(db *sql.DB) {
Я бы здесь предложил использовать функционал взаимодействия с БД который требует context. Сам context брать из request и прокидывать в функцию. Это позволит на больших нагрузках сэкономить походы в БД. Т.к. некоторые клиенты отменяют свои запросы, context помечается как cancel и запрос в БД делаться не будет.

2024-05-13 07:22 UTC, edylcrm commented on internal/server/storage/fileStorage.go
> +		panic(err)
Не стоит использовать паники в бизнес логики. Сама по себе паника это аварийная ситуация и должна завершать приложение. Используется она когда не правильно проинициализировано приложение перед стартом или допущена какая-то грубая ошибка в кода, например nil pointer exception. В остальных случаях всегда лучше использовать error

2024-05-13 07:22 UTC, edylcrm commented on internal/server/storage/fileStorage.go
> +					panic(err)
Здесь тоже самое про панику

2024-05-13 07:22 UTC, edylcrm commented on internal/server/storage/dbStorage.go
> +			panic(err)
Здесь тоже самое про панику

2024-05-13 07:22 UTC, edylcrm commented on internal/server/storage/dbStorage.go
> +		panic(err)
Здесь тоже самое про панику

2024-05-13 07:22 UTC, edylcrm commented on internal/server/storage/dbStorage.go
> +		panic(err)
Здесь тоже самое про панику

2024-05-13 07:22 UTC, edylcrm commented on internal/server/storage/dbStorage.go
> +		panic(err)
Здесь тоже самое про панику

2024-05-13 07:22 UTC, edylcrm commented on internal/server/storage/dbStorage.go
> +		panic(err)
Здесь тоже самое про панику

2024-05-13 07:22 UTC, edylcrm commented on internal/server/storage/saveMem.go
> +		os.Exit(0)
Кажется, что завершать приложение должна main функция, а не функционал по сохранению метрики

2024-05-13 12:46 UTC, stranik28 commented on internal/server/storage/saveMem.go
> +		os.Exit(0)
Это горутина, которая вызывается по завершению работы, она сохраняет и завершает программу

2024-05-15 09:17 UTC, edylcrm requested changes

2024-05-15 09:17 UTC, edylcrm commented on internal/server/storage/saveMem.go
> +			metrics, err = loadMetricsFromDB(c, db)
Подразумевается, что работа с БД будет не только для сохранения данных по аналогии с файлом. Но и поиск select, insert и т.д. Т.е. если приходит env или флаг который подразумевает работы с БД, то работа с memstorage не нужна. Давай все таки это переделаем.

2024-05-16 12:00 UTC, edylcrm approved these changes

2024-05-16 12:00 UTC, edylcrm commented on internal/server/storage/dbStorage.go
> +func InsertMetric(c context.Context, db *sql.DB, metrics []models.Metrics) error {
Я бы здесь сделал отдельную структуру для работы с db и sql.DB. Так же как это сделано с MemStorage для map

2024-05-16 13:09 UTC, merged